-- GRANT OWNERSHIP ON DATABASE PHARMA_COPILOT TO ROLE SYSADMIN COPY CURRENT GRANTS; -- rewrite ownership to different role, preserve other permissions

SHOW CORTEX SEARCH SERVICES LIKE 'SOP_SEARCH_SERVICE';