COMPLETION_MODEL = "llama3.1-8b"
MAX_SEARCH_RESULTS = 4

DATABASE_NAME = "PHARMA_COPILOT"
SCHEMA_NAME = "PHARMA_DATA"
INVENTORY_TABLE = "SN_POOL_SUBTRACT"
SEARCH_SERVICE_NAME = "SOP_SEARCH_SERVICE"
SCHEDULE_TABLE = "SCHEDULE"